[package]
name = "algui"
version = "0.1.0"
description = "Framework to create interactive algorithm visualization"
authors = ["Aloïs Rautureau", "Paul Adam", "Elie Dumont"]
edition = "2021"

[dependencies]
